import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type {
	AgentResult,
	ClientRequest,
	ExecutionClient,
	Provider,
} from '@ergon/shared';
import { listArtifacts, listEvents, openStorageDb } from '@ergon/storage';
import { afterEach, describe, expect, it } from 'vitest';
import { decideManualStep } from '../../cli/src/commands/approve.js';
import { initProject } from '../../cli/src/commands/init.js';
import { getRunStatus, scheduleRun } from '../../cli/src/commands/run.js';
import {
	AgentExecutor,
	ArtifactExecutor,
	ConditionExecutor,
	ExecExecutor,
	ExecutorRegistry,
	ManualExecutor,
	NotifyExecutor,
	startWorker,
} from '../src/index.js';

const tempDirs: string[] = [];

interface WorkflowScenario {
	expectResultOutputs: boolean;
	id: string;
	inputs: Record<string, unknown>;
}

class StubExecutionClient implements ExecutionClient {
	public readonly provider: Provider;

	public constructor(provider: Provider) {
		this.provider = provider;
	}

	public async run(request: ClientRequest): Promise<AgentResult> {
		if (request.signal?.aborted) {
			throw request.signal.reason;
		}

		const prompt = request.prompt ?? '';
		if (
			prompt.includes('Output ONLY the diff') ||
			prompt.includes('Output ONLY a git-compatible unified diff') ||
			prompt.includes('Output ONLY a unified diff')
		) {
			return {
				raw: { kind: 'diff', provider: this.provider },
				text: 'diff --git a/README.md b/README.md\n',
			};
		}

		return {
			raw: { kind: 'json', provider: this.provider },
			text: JSON.stringify({
				affected_components: ['src/runtime.ts'],
				affected_modules: ['engine'],
				api_interfaces: [],
				approach: 'Keep the workflow deterministic and scoped.',
				architecture_context: 'single-worker runtime',
				changes: ['Apply the requested change'],
				commands: {
					install_command: 'true',
					update_command: 'true',
				},
				design_summary: 'Implement the smallest coherent change.',
				diagnosis: 'The repository needs a deterministic change set.',
				documentation_strategy: 'Update the existing docs only where needed.',
				files: ['README.md'],
				files_to_create: [],
				files_to_modify: ['README.md'],
				fix_strategy: 'Apply a minimal safe patch.',
				follow_up_actions: [],
				gaps: [],
				implementation_steps: ['Apply patch', 'Run verification'],
				improvements: [],
				issues: [],
				notes: [],
				optional_improvements: [],
				outdated_sections: [],
				pr_body: 'Body generated by the E2E stub client.',
				pr_description: 'A concise deterministic change.',
				pr_title: 'Stub PR Title',
				proposed_updates: ['README.md'],
				quality_assessment: 'ready',
				required_changes: [],
				risk_assessment: 'low',
				risks: ['low'],
				root_cause: 'Stubbed workflow input for end-to-end coverage.',
				sections_to_modify: ['README'],
				suggested_structure: ['README.md'],
				summary: `Stub summary for ${this.provider}`,
				update_set: [],
				verification: ['true'],
				verification_steps: ['true'],
				writing_guidelines: ['Keep it concise.'],
			}),
		};
	}
}

const scenarios: WorkflowScenario[] = [
	{
		expectResultOutputs: true,
		id: 'code.bump_deps',
		inputs: {
			install_command: 'true',
			new_branch: 'chore/e2e-bump-deps',
			repo_path: 'repo',
			scan_command: 'true',
			test_command: 'true',
			update_command: 'true',
		},
	},
	{
		expectResultOutputs: true,
		id: 'code.codegen',
		inputs: {
			feature: 'Generate a deterministic feature scaffold',
			new_branch: 'feat/e2e-codegen',
			repo_path: 'repo',
			requirements: 'Expose a stable quickstart path',
			test_command: 'true',
		},
	},
	{
		expectResultOutputs: true,
		id: 'code.docs_update',
		inputs: {
			new_branch: 'docs/e2e-update',
			objective: 'Refresh the runtime quickstart documentation',
			repo_path: 'repo',
			validation_command: 'true',
		},
	},
	{
		expectResultOutputs: true,
		id: 'code.hotfix',
		inputs: {
			issue: 'Fix a deterministic edge case in the runtime',
			new_branch: 'hotfix/e2e-runtime',
			repo_path: 'repo',
			test_command: 'true',
		},
	},
	{
		expectResultOutputs: true,
		id: 'code.refactor',
		inputs: {
			new_branch: 'refactor/e2e-runtime',
			repo_path: 'repo',
			task: 'Refactor the runtime smoke path',
			test_command: 'true',
		},
	},
];

function createTempRoot(): string {
	const dir = mkdtempSync(path.join(tmpdir(), 'ergon-library-e2e-'));
	tempDirs.push(dir);
	return dir;
}

function createExecutors(logs: string[]): ExecutorRegistry {
	const clients = new Map<Provider, ExecutionClient>([
		['claude-code', new StubExecutionClient('claude-code')],
		['codex', new StubExecutionClient('codex')],
		['ollama', new StubExecutionClient('ollama')],
		['openclaw', new StubExecutionClient('openclaw')],
		['openrouter', new StubExecutionClient('openrouter')],
	]);

	return new ExecutorRegistry([
		new AgentExecutor({
			resolveClient(provider) {
				const client = clients.get(provider);
				if (!client) {
					throw new Error(`Missing stub client for provider "${provider}"`);
				}
				return client;
			},
		}),
		new ArtifactExecutor(),
		new ConditionExecutor(),
		new ExecExecutor({
			async spawn({ command, signal }) {
				if (signal?.aborted) {
					throw signal.reason;
				}
				const firstLine = command
					.split('\n')
					.map((line) => line.trim())
					.find((line) => line.length > 0);
				return {
					code: 0,
					signal: null,
					stderr: '',
					stdout: `${firstLine ?? 'exec'}\n`,
				};
			},
		}),
		new ManualExecutor(),
		new NotifyExecutor({
			log(message) {
				logs.push(message);
			},
		}),
	]);
}

afterEach(() => {
	for (const dir of tempDirs.splice(0)) {
		rmSync(dir, { force: true, recursive: true });
	}
});

describe('built-in workflow library E2E (phase 5)', () => {
	it.each(
		scenarios,
	)('executes $id end-to-end with the real worker loop', async (scenario) => {
		const rootDir = createTempRoot();
		const dbPath = path.join(rootDir, '.ergon', 'storage', 'ergon.db');
		const logs: string[] = [];
		initProject({ rootDir });
		mkdirSync(path.join(rootDir, 'repo'), { recursive: true });

		const run = scheduleRun(scenario.id, {
			dbPath,
			inputs: JSON.stringify(scenario.inputs),
			rootDir,
		});
		const executors = createExecutors(logs);
		const db = openStorageDb({ dbPath });

		try {
			const firstPass = await startWorker({
				db,
				executors,
				maxRuns: 1,
				pollIntervalMs: 5,
				rootDir,
				workerId: `${scenario.id}-worker-1`,
			});
			expect(firstPass.processedRuns).toBe(1);

			const paused = getRunStatus(run.id, { dbPath, rootDir });
			expect(paused.run.status).toBe('waiting_manual');
			expect(paused.run.current_step_id).toBe('gate');

			const approval = decideManualStep(run.id, 'gate', {
				dbPath,
				decision: 'approve',
				rootDir,
			});
			expect(approval.run.status).toBe('queued');

			const secondPass = await startWorker({
				db,
				executors,
				maxRuns: 1,
				pollIntervalMs: 5,
				rootDir,
				workerId: `${scenario.id}-worker-2`,
			});
			expect(secondPass.processedRuns).toBe(1);

			const completed = getRunStatus(run.id, { dbPath, rootDir });
			expect(completed.run.status).toBe('succeeded');
			expect(
				completed.stepRuns.some((stepRun) => stepRun.step_id === 'notify'),
			).toBe(true);
			if (scenario.expectResultOutputs) {
				expect(completed.run.result_json).toBeTruthy();
			}

			const events = listEvents(db, run.id).map((event) => event.type);
			expect(events).toContain('workflow_scheduled');
			expect(events).toContain('manual_approved');
			expect(events).toContain('workflow_succeeded');

			const artifacts = listArtifacts(db, run.id);
			const summaryArtifact = artifacts.find(
				(artifact) => artifact.name === 'run.summary',
			);
			expect(summaryArtifact).toBeTruthy();
			const summaryFile = path.join(rootDir, summaryArtifact?.path ?? '');
			expect(existsSync(summaryFile)).toBe(true);
			expect(JSON.parse(readFileSync(summaryFile, 'utf8'))).toMatchObject({
				channel: 'stdout',
				workflow_id: scenario.id,
			});
			expect(
				logs.some((entry) =>
					entry.includes(`Workflow completed: ${scenario.id}`),
				),
			).toBe(true);
		} finally {
			db.close();
		}
	});
});
